### ISSUE TITLE
Change default behavior of capability collapsible card to be closed on Capabilities

### ISSUE THREAD

**Issue by ashmilhussain** [sirocco-ventures/raggenie#37]
The current implementation of the capability collapsible card has two issues that need to be addressed to improve user experience:

•	The capability collapsible card is opened by default, keep it closed.
•	An empty capability is created on UI without clicking the **“Add New”** button.

**Required Changes:**

•	Set the capability collapsible card to be closed by default.
•	Create an empty capability only after the user clicks the “Add New” button.

<img width="1496" alt="Screenshot 2024-09-29 at 5 48 17 PM" src="https://github.com/user-attachments/assets/07004a6b-dade-4664-b122-ef29e8b5cc8e">

**Comment by krishnadev7** [comment]
I would like to work on this issue please assign to me

**Comment by agberoz** [comment]
Hey @krishnadev7 ,

Assigning this issue to you, happy coding

If any assistance is required meet our team here: https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by uchiha-vivek** [comment]
**Change default behavior of capability collapsible card to be closed on Capabilities #37**


![default](https://github.com/user-attachments/assets/d5a6245f-d1fb-4699-ac8f-afd4e1eba1d1)

By default no capability is added .


![capability](https://github.com/user-attachments/assets/aaba85e9-f721-422b-989b-d8a17fba3c9f)
When we are adding capability its not in open mode by default state , we need to click it in order to open .

Please assign this issue to me !

**Comment by agberoz** [comment]
@sethumadhavan-k  please review
